api:
  build: ./api
  ports:
    - 8080
  environment:
    - affinity:container!=discovery_api*
users:
  build: ./users
  ports:
    - 8080
  environment:
    - affinity:container!=discovery_users*
registrator:
  image: gliderlabs/registrator
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock
  entrypoint: ["/bin/sh", "-c", "/bin/registrator -ip `wget http://ipinfo.io/ip -qO -` etcd://rysenko.com:4001/registry"]
  net: host
  environment:
    - affinity:container!=discovery_registrator*
