api:
  build: ./api
  ports:
    - 80:8080
users:
  image: cretzel/docker-simple-http-server
  ports:
    - 8080
  environment:
    - affinity:container!=discovery_users*
    - SERVICE_NAME=users
registrator:
  image: gliderlabs/registrator
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock
  entrypoint: ["/bin/sh", "-c", "/bin/registrator -ip `wget http://ipinfo.io/ip -qO -` etcd://rysenko.com:4001/registry"]
  net: host
  environment:
    - affinity:container!=discovery_registrator*
